# Generated by Django 5.0.7 on 2025-07-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50, unique=True)),
                ('inspectionBy', models.CharField(max_length=100)),
                ('inspectionDate', models.DateField()),
                ('bogieDetails', models.JSONField()),
                ('bogieChecksheet', models.JSONField()),
                ('bmbcChecksheet', models.JSONField()),
            ],
        ),
    ]
